<a href="https://colab.research.google.com/github/rsanthosh99/Deep_Learning_UT/blob/main/MIS_285_HW_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MIS 285N: Homework 1

Submit:

A pdf of your notebook with solutions.
A link to your colab notebook or also upload your .ipynb if not working on colab.

# Goals of this Lab

**Fully Connected Models and XOR**


1. How to create data objects that pytorch can use
2. How to create a dataloader
3. How to define a basic fully connected single layer model
4. How to define a multi-layer fully connected model
5. How to add non-linear activation functions.
6. How to add layers in two different ways

We also see the importance of nonlinear activation functions directly, by experimenting with the simple 4-data-point XOR example that we saw in class.


In [9]:
import torch
import numpy as np
import time
from tqdm.notebook import tqdm

# First we define a linear regressor.
This is the same as a fully connected layer. It will be a building block in making deeper neural networks with fully connected layers.

In [12]:
# We define our first class: LinearRegressor
#
class LinearRegressor(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        """
        Define the layer(s) needed for the linear model.
        """
        super().__init__()
        self.linear = torch.nn.Linear(input_dim, output_dim, bias = True) # just linear

    def forward(self, x):
        """
        Calculate the regression score (MSE).

        Input:
            x (float tensor N x d): input rows
        Output:
            y (float tensor N x 1): regression output
        """
        x = self.linear(x)
        return torch.flatten(x)


    # defining a separate predict function is useful for multi-class
    # classification as we will see later. Here it is
    # unnecessary.

    def predict(self, x):
        """
        Predict the regression label of the input vector.

        Input:
            x (float tensor N X d): input images
        Output:
            y (float tensor N x 1): regression output
        """
        x = self.linear(x)
        return torch.flatten(x)




## Problem 1:

Now you will use torch.nn.Sequential (see https://pytorch.org/docs/stable/generated/torch.nn.Sequential.html) to construct a two layer neural network, with two fully connected layers (no non-linearity yet). Thus, you will combine torch.nn.Sequential with torch.nn.Linear that you saw above.


Design your network so that the first layer has as many neurons as the input.

Note: you have only one line to fill in here.

In [23]:
class TwoLayerLinearRegressor(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        """
        Define a model that stacks two linear fully connected layers.
        """
        super().__init__()
        self.TLL = torch.nn.Sequential(
              torch.nn.Linear(input_dim, input_dim),
              torch.nn.Linear(input_dim, output_dim)
              )

    def forward(self, x):
        """
        Calculate the regression score (MSE).

        Input:
            x (float tensor N x d): input rows
        Output:
            y (float tensor N x 1): regression output
        """
        x = self.TLL(x)
        return torch.flatten(x)

    def predict(self, x):
        """
        Predict the regression label of the input vector.

        Input:
            x (float tensor N X d): input images
        Output:
            y (float tensor N x 1): regression output
        """
        x = self.TLL(x)
        return torch.flatten(x)






## Problem 2

Now you will create the same network, but using different syntax: you will not use torch.nn.Sequential. You need to fill in the two lines as noted by the comments.

In [24]:
class TwoLayerLinearRegressor2(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        """
        Define a model that stacks two linear fully connected layers.
        """
        super().__init__()
        self.fc1 = torch.nn.Linear(input_dim, input_dim)
        self.fc2 = torch.nn.Linear(input_dim, output_dim)

    def forward(self, x):
        """
        Calculate the regression score (MSE).

        Input:
            x (float tensor N x d): input rows
        Output:
            y (float tensor N x 1): regression output
        """

        x = self.fc1(x)
        x = self.fc2(x)
        return torch.flatten(x)

    def predict(self, x):
        """
        Predict the regression label of the input vector.

        Input:
            x (float tensor N X d): input images
        Output:
            y (float tensor N x 1): regression output
        """
        x = self.fc1(x)
        x = self.fc2(x)
        return torch.flatten(x)


## Problem 3

Now you will define a 2 layer neural network with ReLU activation at the first layer. In other words:

Let $x$ be the input.
Then writing $z = Wx + c$, $h=$ReLU$(z)$ is the first layer's neurons. Then the output is $y = w\cdot z+d$.

Create this neural network using the torch.nn.Sequential command. Conceptually, it may help to realize that this neural network is: a fully connected layer followed by a ReLU, followed by a fully connected layer.

Also see: https://pytorch.org/docs/stable/generated/torch.nn.ReLU.html

Note: You have only one line to fill in here.

In [25]:
class TwoLayerNonLinearRegressor(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        """
        Define a model that has a linear layer, a ReLU layer and another linear layer.
        """
        super().__init__()
        self.linear = torch.nn.Sequential(torch.nn.Linear(input_dim, input_dim),  torch.nn.ReLU(), torch.nn.Linear(input_dim, output_dim))
    def forward(self, x):
        """
        Calculate the regression score (MSE).

        Input:
            x (float tensor N x d): input rows
        Output:
            y (float tensor N x 1): regression output
        """
        x = self.linear(x)
        return torch.flatten(x)

    def predict(self, x):
        """
        Predict the regression label of the input vector.

        Input:
            x (float tensor N X d): input images
        Output:
            y (float tensor N x 1): regression output
        """
        x = self.linear(x)
        return torch.flatten(x)



## Problem 4

Do this one more time, but now without torch.nn.Sequential.

You have three lines to fill in here.

In [26]:
# We now do this again, without using nn.sequential
# in order to illustrate different syntax.

class TwoLayerNonLinearRegressor2(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        """
        Define a model that has a linear layer, a ReLU layer and another linear layer.
        """
        super().__init__()
        self.fc1 = torch.nn.Linear(input_dim, input_dim)
        self.relu = torch.nn.ReLU()
        self.fc2 = torch.nn.Linear(input_dim, output_dim)

    def forward(self, x):
        """
        Calculate the regression score (MSE).

        Input:
            x (float tensor N x d): input rows
        Output:
            y (float tensor N x 1): regression output
        """

        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return torch.flatten(x)

    def predict(self, x):
        """
        Predict the regression label of the input vector.

        Input:
            x (float tensor N X d): input images
        Output:
            y (float tensor N x 1): regression output
        """
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return torch.flatten(x)

## Problem 5 (Nothing to turn in)

Read the documentation https://pytorch.org/docs/stable/optim.html to see what are the options pytorch provides for an optimizer, and what the parameters are.

In [17]:
# Now we define a function for training
# Note each of the arguments that it takes

def train(model, data_train, data_val, device, lr=0.01, epochs=5000):
    """
    Train the model.

    Input:
      model (torch.nn.Module): the model to train
      data_train (torch.utils.data.Dataloader): yields batches of data
      data_val (torch.utils.data.Dataloader): use this to validate your model
      device (torch.device): which device to use to perform computation

      (optional) lr: learning rate hyperparameter
      (optional) epochs: number of passes over dataloader
    """

    # Setup the loss function to use: mean squared error
    loss_function = torch.nn.MSELoss(reduction = 'sum')

    # Setup the optimizer -- just generic ADAM
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    # Wrap in a progress bar.
    for epoch in tqdm(range(epochs)):
        # Set the model to training mode.
        model.train()

        for x, y in data_train:
            x = x.to(device)
            y = y.to(device)

            # Forward pass through the network
            output = model(x)

            # Compute loss
            loss = loss_function(output, y)

            # update model weights.
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

        # Set the model to eval mode and compute accuracy.
        model.eval()

        accuracys_val = list()

        for x, y in data_val:
            x = x.to(device)
            y = y.to(device)

            y_pred = model.predict(x)

In [18]:
# We write a function that takes a model, evaluate on the validation
# data set and returns the predictions

def evaluate_model(model,data_val,device):
  model.eval()
  output_vals = list()
  accuracys_val = list()
  for x, y in data_val:
            x = x.to(device)
            y = y.to(device)

            y_pred = model.predict(x)
            output_vals.append(y_pred)
            # accuracy_val = (y_pred == y).float().mean().item()
            # accuracys_val.append(accuracy_val)

  # accuracy = torch.FloatTensor(accuracys_val).mean().item()
  return output_vals

## Problem 6 (Nothing to turn in)

Read the documentation and try to understand what a dataloader is. You can start here https://pytorch.org/docs/stable/data.html but there are many tutorials out there as well.

In [19]:
import numpy as np
# Creating the data: Linear Regression on Linear Data
from torch.utils.data import TensorDataset, DataLoader
N = 15
X = np.random.randn(N,3)
beta = np.array([1,-1,2])
Y = np.dot(X,beta)
tensor_x = torch.Tensor(X) # transform to torch tensor
tensor_y = torch.Tensor(Y)
print('These are the labels:\n',Y)
print('These are the features:\n',X)

m = 1 # Batch size
data = TensorDataset(tensor_x,tensor_y) # create your datset
data_train = DataLoader(data,batch_size = m, shuffle = True) # create your dataloader with training data
data_val = DataLoader(data) # create your dataloader with validation data, here same as training

These are the labels:
 [-0.22853653 -0.8369304   0.38693409 -0.57507427  4.17961173 -1.13406339
 -1.16167357  3.99714745 -1.34947889 -2.72932195  1.51817797 -1.18347261
 -4.59993721 -2.02846486 -1.12325124]
These are the features:
 [[ 0.31650525  1.09056039  0.2727593 ]
 [-0.84650142  1.29840367  0.65398734]
 [ 0.96782376  0.20118207 -0.1898538 ]
 [ 1.46438325  1.88474418 -0.07735667]
 [ 0.48826808  0.45865945  2.07500156]
 [-0.38558949  1.59687021  0.42419816]
 [ 0.08172107  0.50584879 -0.36877293]
 [ 1.29188198 -0.71209382  0.99658583]
 [-0.2151147   0.45694632 -0.33870893]
 [-1.21975608  0.39544414 -0.55706086]
 [ 0.32272742  0.11614709  0.65579882]
 [ 0.67717048  0.59473396 -0.63295456]
 [-1.67494344  1.0762895  -0.92435214]
 [ 0.39151539  1.5872391  -0.41637057]
 [-0.40938421 -0.49949254 -0.60667979]]


## Now we train and evaluate the linear model.

In [20]:
# Define the model we wish to use, and train it.
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model = LinearRegressor(3, 1)
model.to(device)

train(model, data_train, data_val, device)

  0%|          | 0/5000 [00:00<?, ?it/s]

## Here is some code for getting the parameters of the model.

In [21]:
# Now let's get the model parameters.
# We can see that we have succeeded in learning beta: [1,-1,2]
for name, param in model.named_parameters():
  print (name, param.data)

# If we wanted to, we could also only print the ones that we update (may be useful for more complex models)
"""
for name, param in model.named_parameters():
    if param.requires_grad:
        print (name, param.data)
"""

linear.weight tensor([[ 0.9757, -0.9860,  1.9707]])
linear.bias tensor([0.0039])


'\nfor name, param in model.named_parameters():\n    if param.requires_grad:\n        print (name, param.data)\n'

In [34]:
# Now let's move to our second model: the two layer linear regressor.
# We again define the model using the class we created.
# Then we train the model, as above.

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model2 = TwoLayerLinearRegressor(3, 1)
model2.to(device)

train(model2, data_train, data_val, device)

  0%|          | 0/5000 [00:00<?, ?it/s]

In [35]:
# Let's see how well this model agrees with the training data
output_values = evaluate_model(model2,data_val,device)
print('Ground Truth:\n',Y)
print('Model Output:\n',output_values)

Ground Truth:
 [-0.22853653 -0.8369304   0.38693409 -0.57507427  4.17961173 -1.13406339
 -1.16167357  3.99714745 -1.34947889 -2.72932195  1.51817797 -1.18347261
 -4.59993721 -2.02846486 -1.12325124]
Model Output:
 [tensor([-0.2324], grad_fn=<ViewBackward0>), tensor([-0.8394], grad_fn=<ViewBackward0>), tensor([0.3899], grad_fn=<ViewBackward0>), tensor([-0.5985], grad_fn=<ViewBackward0>), tensor([4.1288], grad_fn=<ViewBackward0>), tensor([-1.1466], grad_fn=<ViewBackward0>), tensor([-1.1741], grad_fn=<ViewBackward0>), tensor([3.9603], grad_fn=<ViewBackward0>), tensor([-1.3615], grad_fn=<ViewBackward0>), tensor([-2.7441], grad_fn=<ViewBackward0>), tensor([1.5440], grad_fn=<ViewBackward0>), tensor([-1.2023], grad_fn=<ViewBackward0>), tensor([-4.6100], grad_fn=<ViewBackward0>), tensor([-2.0208], grad_fn=<ViewBackward0>), tensor([-1.1366], grad_fn=<ViewBackward0>)]


# The XOR Data Set
We see that linear layers do not suffice.

In [29]:
"""
Here we create the simple XOR data set an a numpy array.
Then we make X and Y into tensor objects that torch uses,
and we package it into a Dataset object called data.
Then we create a DataLoader.
"""

Xxor = np.array([[0,0],[0,1],[1,0],[1,1]])
Yxor = np.array([0,1,1,0])
tensor_xxor = torch.Tensor(Xxor) # transform to torch tensor
tensor_yxor = torch.Tensor(Yxor)
print('These are the labels:\n',Yxor)
print('These are the features:\n',Xxor)

dataxor = TensorDataset(tensor_xxor,tensor_yxor) # create your datset
dataxor_train = DataLoader(dataxor) # create your dataloader with training data
dataxor_val = DataLoader(dataxor) # create your dataloader with validation data, here same as training

These are the labels:
 [0 1 1 0]
These are the features:
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]


## Problem 7

Train your linear regressor on these data. Now see how well you do, by evaluating your solution on the training data. Remember the values we got in class.

Your output here should be predicted values for each of the 4 points in our XOR data set.

In [32]:
# Now we train a linear classifier on these data.
# We know (and can verify) that this will fail because no linear classifier can succeed

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model3 = TwoLayerLinearRegressor(2, 1)
model3.to(device)

train(model3, dataxor_train, dataxor_val, device)
output_values = evaluate_model(model3,dataxor_val,device)
print('Ground Truth:\n',Yxor)
print('Model Output:\n',output_values)

  0%|          | 0/5000 [00:00<?, ?it/s]

Ground Truth:
 [0 1 1 0]
Model Output:
 [tensor([0.5005], grad_fn=<ViewBackward0>), tensor([0.5005], grad_fn=<ViewBackward0>), tensor([0.5005], grad_fn=<ViewBackward0>), tensor([0.5005], grad_fn=<ViewBackward0>)]


## Problem 8

Now repeat this, but using both versions of your non-linear two-layer model. Thus: train both versions of your non-linear two layer models, and evaluate them on the data.  

If you did this correctly, the values you compute should equal (approximately) the values of the XOR function.

In [46]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model4 = TwoLayerNonLinearRegressor(2, 1)
model4.to(device)

train(model4, dataxor_train, dataxor_val, device, lr=0.01, epochs=5000)
output_values = evaluate_model(model4,dataxor_val,device)
print('Ground Truth - NL Version 1:\n',Yxor)
print('Model Output - NL Version 1:\n',output_values)



  0%|          | 0/5000 [00:00<?, ?it/s]

Ground Truth - NL Version 1:
 [0 1 1 0]
Model Output - NL Version 1:
 [tensor([1.0431e-07], grad_fn=<ViewBackward0>), tensor([1.], grad_fn=<ViewBackward0>), tensor([1.], grad_fn=<ViewBackward0>), tensor([-3.7253e-09], grad_fn=<ViewBackward0>)]


In [43]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model5 = TwoLayerNonLinearRegressor2(2, 1)
model5.to(device)

train(model5, dataxor_train, dataxor_val, device, lr=0.01, epochs=5000)
output_values = evaluate_model(model5,dataxor_val,device)
print('Ground Truth - NL Version 2:\n',Yxor)
print('Model Output - NL Version 2:\n',output_values)

  0%|          | 0/5000 [00:00<?, ?it/s]

Ground Truth - NL Version 2:
 [0 1 1 0]
Model Output - NL Version 2:
 [tensor([0.], grad_fn=<ViewBackward0>), tensor([1.], grad_fn=<ViewBackward0>), tensor([1.], grad_fn=<ViewBackward0>), tensor([0.], grad_fn=<ViewBackward0>)]


## Problem 9

Print the parameters of one of your non-linear models. Thus, you should print: 4 weights plus 2 bias values for the first layer, and then 2 weights plus 1 bias value for the second: 9 parameters in total.

In [47]:
for name, param in model4.named_parameters():
  print (name, param.data)


linear.0.weight tensor([[ 1.2912, -1.2682],
        [-1.4338,  1.4175]])
linear.0.bias tensor([-0.0090,  0.0828])
linear.2.weight tensor([[0.8255, 0.7055]])
linear.2.bias tensor([-0.0584])


In [45]:
for name, param in model5.named_parameters():
  print (name, param.data)


fc1.weight tensor([[-0.6488, -0.4693],
        [ 0.8043,  0.8511]])
fc1.bias tensor([-0.0471, -0.9198])
fc2.weight tensor([[-0.2774, -0.9066]])
fc2.bias tensor([0.6675])
